/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 donut.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/donut.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.donut007.geometry}
        material={materials["Material.002"]}
        position={[0, 0, 0]}
        rotation={[-0.039, 0.878, -0.055]}>
        <mesh
          geometry={nodes.icing006.geometry}
          material={materials["Material.006"]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/donut.glb");
